CREATE SEQUENCE IF NOT EXISTS seq1 
	increment 1 
	start 1;
CREATE SEQUENCE IF NOT EXISTS seq2 
	increment 1 
	start 1;

CREATE TABLE SEX(
  SEX_ID SERIAL PRIMARY KEY,
  GENDER VARCHAR(20)
);
INSERT INTO SEX(GENDER) VALUES('male');
INSERT INTO SEX(GENDER) VALUES('female');
INSERT INTO SEX(GENDER) VALUES('unknown');
SELECT * FROM SEX;

CREATE TABLE PHONE_TYPE(
  PHONE_ID SERIAL PRIMARY KEY,
  PHONE_TYPE VARCHAR(20)
);
INSERT INTO PHONE_TYPE(PHONE_TYPE) VALUES('CELL');
INSERT INTO PHONE_TYPE(PHONE_TYPE) VALUES('LANDLINE');
SELECT * FROM PHONE_TYPE;


CREATE TABLE ADDRESS_TYPES(
  ADDRESS_ID SERIAL PRIMARY KEY,
  ADDRESS_TYPE VARCHAR(20)
);
INSERT INTO ADDRESS_TYPES(ADDRESS_TYPE) VALUES('WORK');
INSERT INTO ADDRESS_TYPES(ADDRESS_TYPE) VALUES('HOME');
SELECT * FROM ADDRESS_TYPES;


CREATE TABLE RACE_TYPE(
  RACE_ID SERIAL PRIMARY KEY,
  RACE_TYPE VARCHAR(20)
);
INSERT INTO RACE_TYPE(RACE_TYPE) VALUES('ASIAN');
INSERT INTO RACE_TYPE(RACE_TYPE) VALUES('AMERICAN');
SELECT * FROM RACE_TYPE;

CREATE TABLE RACE(
  RACE_ID SERIAL PRIMARY KEY,
  RACE_TYPE INT NOT NULL,
  PATIENT_ID VARCHAR(20),
  CONSTRAINT race_id FOREIGN KEY(RACE_TYPE) REFERENCES RACE_TYPE(RACE_ID)
);
INSERT INTO RACE(RACE_TYPE,PATIENT_ID) VALUES(1,'0001');
SELECT * FROM RACE;

CREATE TABLE IF NOT EXISTS Patient(
  PATIENT_ID CHAR(20) NOT NULL DEFAULT to_char(nextval('seq1'),'0000FM'),
  CHART_NUMBER CHAR(20) NOT NULL DEFAULT to_char(nextval('seq2'),'EMP0000FM'),
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  MIDDLE_NAME VARCHAR(20),
  DOB DATE,
  SEX INT,
  RACE INT,
  PRIMARY KEY(PATIENT_ID),
  CONSTRAINT sex_constraint FOREIGN KEY(SEX) REFERENCES SEX(SEX_ID),
  CONSTRAINT race_constraint FOREIGN KEY(RACE) REFERENCES RACE(RACE_ID)
);
INSERT into Patient (FIRST_NAME,LAST_NAME,MIDDLE_NAME,SEX,RACE) VALUES ('NIKITA','MIRCHANDANI','M',2,1);
INSERT into Patient (FIRST_NAME,LAST_NAME,MIDDLE_NAME,SEX,RACE) VALUES ('fb','dv','M',1,1);
SELECT * from Patient;

CREATE TABLE ADDRESS(
  ADDRESS_ID SERIAL PRIMARY KEY,
  ADDRESS_TYPE INT NOT NULL,
  STREET VARCHAR(20),
  CITY VARCHAR(20),
  ZIP INT,
  STATE VARCHAR(20),
  COUNTRY VARCHAR(20),
  PATIENT_ID VARCHAR(20),
  CONSTRAINT user_id FOREIGN KEY(PATIENT_ID) REFERENCES Patient(PATIENT_ID),
  CONSTRAINT ADDRESS_TYPE_CONSTRAINT FOREIGN KEY(ADDRESS_TYPE) REFERENCES ADDRESS_TYPES(ADDRESS_ID)
);
INSERT INTO ADDRESS(ADDRESS_TYPE,STREET,CITY,ZIP,PATIENT_ID) VALUES(1,'STREET','rajkot',387630,'0001');
SELECT * FROM ADDRESS;

CREATE TABLE PHONE(
  PHONE_ID SERIAL PRIMARY KEY,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  PHONE_TYPE INT,
  PRIMARY_PHONE BOOLEAN,
  ADDRESS_ID INT,
  CONSTRAINT address_id_constraint FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
  CONSTRAINT phone_type_constraint FOREIGN KEY(PHONE_TYPE) REFERENCES PHONE_TYPE(PHONE_ID)
);
INSERT into PHONE(PHONE_NUMBER,PHONE_TYPE,PRIMARY_PHONE,ADDRESS_ID) VALUES (8849126581,1,false,1);
SELECT * from PHONE;

CREATE TABLE FAX(
  FAX_ID SERIAL PRIMARY KEY,
  FAX_NUMBER VARCHAR(10) NOT NULL,
  PRIMARY_FAX BOOLEAN
);
INSERT into FAX(FAX_NUMBER,PRIMARY_FAX) VALUES (5313,false);
SELECT * from FAX;







